### PR TITLE
Fix web-animations uncaught TypeError

### LINKED ISSUE #29: web-animations uncaught TypeError (a fix is included)
# Submit an Issue

Hi,

Thank you guys for having developed this useful component/wrapper.

Unfortunately, I've found a bug when using your component in addition to other polymer elements (paper-tooltip for example).

Your component has a file "px-app-nav.html" that uses this script:
**<script src="../web-animations-js/web-animations-next.min.js"></script>**

Whilst, paper-tooltip uses neon-animation that uses behind this script:
**<script src="../web-animations-js/web-animations-next-lite.min.js"></script>**

The errors I got:

- px-app-nav is not collapsable anymore and this error is displayed in the console:
**web-animations-next-animation.js:41 Uncaught TypeError: Cannot read property 'cancel' of null(…)**
- Multiple entries are highlighted in your component
- Other components are not working correctly (paper-tooltip for example) 

I fixed this issue by replacing in your file "px-app-nav.html" that specific line by this:
**<script src="../web-animations-js/web-animations.min.js"></script>**

This little modification fixed all the issues I got and had no side effects on your component.

Can you take a look at it ?

Cheers,

Arslan

## Steps to reproduce the problem:
Importing paper-tooltip or any other polymer component that uses web-animations-next-lite.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Chrome/Opera latest stable version
Latest (at this day) version of px-app-nav and paper-tooltip

### PR DESCRIPTION
**Pull request by sjw787**
Fixes #29 using change proposed by @ArslanBouzid.

# Pull Request

Hi,

Thanks for helping us improve the Predix UI platform by submitting a Pull Request.

To help us merge your Pull Request as fast as possible, please fill out the following sections:

* ## A description of the changes proposed in the pull request:
Replace reference to `web-animations-js/web-animations-next.min.js` with `web-animations-js/web-animations.min.js`

* ## A reference to a related issue (if applicable):
#29

* ## @mentions of the person or team responsible for reviewing proposed changes:
@mdwragg

* ## working tests:

### CODE REVIEW

**Comment by mdwragg** [comment]
Thanks for the PR, I think we were working on it at the same time :-(

Fixed in 435879a

**Comment by sjw787** [comment]
Oh okay haha. I saw that you requested for one of us to make it and it was a small change so I went ahead and did it. No worries and thank you!

**Comment by mdwragg** [comment]
We both came to the same conclusion so no worries ;-) thanks for taking the time, we really appreciate it. Looking forward to future PRs! 💯

**Comment by ArslanBouzid** [comment]
Thank you guys for the fix :) 
I can finally use your repo instead of my fork.

**Pull request closed without merging**
